<?php

namespace Alala\MoviedbBundle\Repository;

/**
 * MoviePeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviePeopleRepository extends \Doctrine\ORM\EntityRepository
{
}
